#!/bin/bash
# Bitnami postgresql-env.sh compatibility script

# PostgreSQL environment configuration for Bitnami compatibility

# Set default PostgreSQL directories
export POSTGRESQL_VOLUME_DIR="${POSTGRESQL_VOLUME_DIR:-/bitnami/postgresql}"
export POSTGRESQL_DATA_DIR="${POSTGRESQL_DATA_DIR:-$POSTGRESQL_VOLUME_DIR/data}"
export POSTGRESQL_CONF_DIR="${POSTGRESQL_CONF_DIR:-/opt/bitnami/postgresql/conf}"
export POSTGRESQL_LOG_DIR="${POSTGRESQL_LOG_DIR:-/opt/bitnami/postgresql/logs}"
export POSTGRESQL_TMP_DIR="${POSTGRESQL_TMP_DIR:-/opt/bitnami/postgresql/tmp}"
export POSTGRESQL_SECRETS_DIR="${POSTGRESQL_SECRETS_DIR:-/opt/bitnami/postgresql/secrets}"
export POSTGRESQL_CERTS_DIR="${POSTGRESQL_CERTS_DIR:-/opt/bitnami/postgresql/certs}"

# Set PostgreSQL binary paths
export POSTGRESQL_BIN_DIR="${POSTGRESQL_BIN_DIR:-/usr/bin}"
export POSTGRESQL_BASE_DIR="${POSTGRESQL_BASE_DIR:-/opt/bitnami/postgresql}"

# Set PostgreSQL configuration
export POSTGRESQL_PORT_NUMBER="${POSTGRESQL_PORT_NUMBER:-5432}"
export POSTGRESQL_DEFAULT_DATABASE="${POSTGRESQL_DEFAULT_DATABASE:-postgres}"
export POSTGRESQL_DEFAULT_USER="${POSTGRESQL_DEFAULT_USER:-postgres}"

# Set PGDATA for compatibility
export PGDATA="${PGDATA:-$POSTGRESQL_DATA_DIR}"

# Set system user
export POSTGRESQL_DAEMON_USER="${POSTGRESQL_DAEMON_USER:-bitnami}"
export POSTGRESQL_DAEMON_GROUP="${POSTGRESQL_DAEMON_GROUP:-bitnami}"

# Map Bitnami variables to PostgreSQL standard variables
if [[ -n "${POSTGRES_PASSWORD:-}" ]]; then
    export POSTGRESQL_PASSWORD="$POSTGRES_PASSWORD"
fi

if [[ -n "${POSTGRES_USER:-}" ]]; then
    export POSTGRESQL_USERNAME="$POSTGRES_USER"
fi

if [[ -n "${POSTGRES_DATABASE:-}" ]]; then
    export POSTGRESQL_DATABASE="$POSTGRES_DATABASE"
fi

# Handle password files
if [[ -n "${POSTGRES_PASSWORD_FILE:-}" ]] && [[ -f "$POSTGRES_PASSWORD_FILE" ]]; then
    export POSTGRESQL_PASSWORD="$(cat "$POSTGRES_PASSWORD_FILE")"
fi

if [[ -n "${POSTGRES_POSTGRES_PASSWORD_FILE:-}" ]] && [[ -f "$POSTGRES_POSTGRES_PASSWORD_FILE" ]]; then
    export POSTGRESQL_POSTGRES_PASSWORD="$(cat "$POSTGRES_POSTGRES_PASSWORD_FILE")"
fi

# Replication settings
export POSTGRESQL_REPLICATION_MODE="${POSTGRES_REPLICATION_MODE:-}"
export POSTGRESQL_REPLICATION_USER="${POSTGRES_REPLICATION_USER:-}"
export POSTGRESQL_REPLICATION_PASSWORD="${POSTGRES_REPLICATION_PASSWORD:-}"

if [[ -n "${POSTGRES_REPLICATION_PASSWORD_FILE:-}" ]] && [[ -f "$POSTGRES_REPLICATION_PASSWORD_FILE" ]]; then
    export POSTGRESQL_REPLICATION_PASSWORD="$(cat "$POSTGRES_REPLICATION_PASSWORD_FILE")"
fi

# Cluster settings
export POSTGRESQL_CLUSTER_APP_NAME="${POSTGRES_CLUSTER_APP_NAME:-}"
export POSTGRESQL_SYNCHRONOUS_COMMIT_MODE="${POSTGRES_SYNCHRONOUS_COMMIT_MODE:-}"
export POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS="${POSTGRES_NUM_SYNCHRONOUS_REPLICAS:-}"

# Standby settings
export POSTGRESQL_MASTER_HOST="${POSTGRES_MASTER_HOST:-}"
export POSTGRESQL_MASTER_PORT_NUMBER="${POSTGRES_MASTER_PORT_NUMBER:-5432}"

# Init settings
export POSTGRESQL_INITDB_ARGS="${POSTGRES_INITDB_ARGS:-}"
export POSTGRESQL_INITDB_WALDIR="${POSTGRES_INITDB_WALDIR:-}"
export POSTGRESQL_INITSCRIPTS_USERNAME="${POSTGRES_INITSCRIPTS_USERNAME:-}"
export POSTGRESQL_INITSCRIPTS_PASSWORD="${POSTGRES_INITSCRIPTS_PASSWORD:-}"

# LDAP settings
export POSTGRESQL_ENABLE_LDAP="${POSTGRESQL_ENABLE_LDAP:-no}"
export POSTGRESQL_LDAP_URL="${POSTGRESQL_LDAP_URL:-}"
export POSTGRESQL_LDAP_SERVER="${POSTGRESQL_LDAP_SERVER:-}"
export POSTGRESQL_LDAP_PORT="${POSTGRESQL_LDAP_PORT:-389}"
export POSTGRESQL_LDAP_SCHEME="${POSTGRESQL_LDAP_SCHEME:-}"
export POSTGRESQL_LDAP_TLS="${POSTGRESQL_LDAP_TLS:-}"
export POSTGRESQL_LDAP_PREFIX="${POSTGRESQL_LDAP_PREFIX:-}"
export POSTGRESQL_LDAP_SUFFIX="${POSTGRESQL_LDAP_SUFFIX:-}"
export POSTGRESQL_LDAP_BASE_DN="${POSTGRESQL_LDAP_BASE_DN:-}"
export POSTGRESQL_LDAP_BIND_DN="${POSTGRESQL_LDAP_BIND_DN:-}"
export POSTGRESQL_LDAP_BIND_PASSWORD="${POSTGRESQL_LDAP_BIND_PASSWORD:-}"
export POSTGRESQL_LDAP_SEARCH_ATTR="${POSTGRESQL_LDAP_SEARCH_ATTR:-}"
export POSTGRESQL_LDAP_SEARCH_FILTER="${POSTGRESQL_LDAP_SEARCH_FILTER:-}"