# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: keycloak
      image: quay.io/keycloak/keycloak:26.3.5
    - name: keycloak-config-cli
      image: docker.io/adorsys/keycloak-config-cli:6.4.0
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 26.3.5
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://ghcr.io/sammyeby/charts
    version: 17.x.x
  - name: common
    repository: oci://ghcr.io/sammyeby/charts
    tags:
      - bitnami-common
    version: 2.x.x
description:
  Keycloak is a high performance Java-based identity and access management
  solution. It lets developers add an authentication layer to their applications with
  minimum effort.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
  - keycloak
  - access-management
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: keycloak
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
version: 25.2.4
