name: Build and Push Custom PostgreSQL Image

on:
  push:
    branches: [main]
    paths:
      - "docker/postgresql/**"
  pull_request:
    branches: [main]
    paths:
      - "docker/postgresql/**"
  workflow_dispatch:
    inputs:
      postgresql_version:
        description: "PostgreSQL version to build"
        required: false
        default: "17"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sammyeby/bitnami-postgresql

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ github.event.inputs.postgresql_version || '17' }}
            type=raw,value=${{ github.event.inputs.postgresql_version || '17' }}-minimal
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=minimal,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/postgresql
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            POSTGRESQL_VERSION=${{ github.event.inputs.postgresql_version || '17' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image details
        run: |
          echo "Built and pushed image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
